version: "3.4"

services:
  api:
    image: tryaspnetcore.api:0.1
    build:
      context: src/TryAspNetCore.Api
    ports:
      - "9999:80"
    command: bash -c 'while !</dev/tcp/postgres_db/5432; do sleep 1; done; dotnet TryAspNetCore.Api.dll'
    networks:
      - tryaspnetcore
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:11.1-alpine
    ports:
      - "5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "deneme"
      POSTGRES_DB: "TryAspNetCore"
    networks:
      - tryaspnetcore

volumes:
  db_volume:

networks:
  tryaspnetcore:
    driver: bridge
